"""convert_embedding_to_pgvector

Revision ID: 97c14d946ec6
Revises: 0bdf94b9f661
Create Date: 2025-03-02 16:11:15.734100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '97c14d946ec6'
down_revision: Union[str, None] = '0bdf94b9f661'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'embedding',
               existing_type=postgresql.ARRAY(sa.REAL()),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               type_=postgresql.ARRAY(sa.REAL()),
               existing_nullable=True)
    # ### end Alembic commands ###
